// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    cert_skills
    (
        init => init
        issueCertificate => issue_certificate
        revokeCertificate => revoke_certificate
        getCertificate => get_certificate
        getUserCertificates => get_user_certificates
        getIssuerCertificates => get_issuer_certificates
        getLastCertificateId => last_certificate_id
        getCertificateById => certificate
        getUserCertificatesIds => address_certificates
        getIssuerCertificatesIds => address_issued_certificates
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
